- hosts: all
  connection: local
  become: yes
  tasks:
  - name: install Python3
    package:
      name:
        - python3
        - python3-pip
      state: present

- hosts: wordpress
  connection: local
  roles:
    - server
    - php
    - mysql
    - wordpress
